name: build-and-release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag (e.g. v1.0.0)"
        required: true
        default: "v0.0.1"

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -Ls https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          uv sync
          uv add pyinstaller
          uv run pyinstaller --onefile main.py --name tnl
          mkdir -p release
          mv dist/tnl release/tnl

      - name: Upload linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: release/tnl

  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        shell: pwsh
        run: |
          irm https://astral.sh/uv/install.ps1 | iex
          echo "$env:USERPROFILE\.cargo\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

      - name: Build
        shell: pwsh
        run: |
          uv sync
          uv add pyinstaller
          uv run pyinstaller --onefile main.py --name tnl

          New-Item -ItemType Directory -Force release | Out-Null
          Copy-Item dist\tnl.exe release\tnl.exe

      - name: Upload windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: release/tnl.exe

  release:
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.tag }}
          files: |
            linux/tnl
            windows/tnl.exe
